const metrics = [['Total users', '75,800', '+8.5%', 'text-green'], ['Revenue', '$4,300', '+6.8%', 'text-green'], ['New orders', '1,245', '-2.1%', 'text-red'], ['Conversion rate', '3.6%', '+1.2%', 'text-green']]
const activity = [['New client registered', '2 minutes ago'], ['Invoice #5482 was paid', '18 minutes ago'], ['Quarterly report is ready', '1 hour ago'], ['Marketing campaign scheduled', 'Today, 09:42']]

export default function DashboardPage() {
  return <div className="page">
    <aside className="navbar navbar-vertical navbar-expand-lg" aria-label="Main navigation"><div className="container-fluid"><a className="navbar-brand navbar-brand-autodark" href="/">TABLER</a><nav className="navbar-nav pt-lg-3"><a className="nav-link active" href="/"><span className="nav-link-title">Dashboard</span></a><a className="nav-link" href="#analytics"><span className="nav-link-title">Analytics</span></a><a className="nav-link" href="#projects"><span className="nav-link-title">Projects</span></a><a className="nav-link" href="#team"><span className="nav-link-title">Team</span></a></nav></div></aside>
    <div className="page-wrapper"><header className="navbar navbar-expand-md d-print-none"><div className="container-xl"><div className="navbar-nav flex-row order-md-last"><div className="nav-item"><span className="avatar avatar-sm" style={{ backgroundImage: "url('/static/avatars/074m.jpg')" }} /></div></div><div className="navbar-nav"><span className="nav-link">Welcome back, Alex</span></div></div></header>
      <main className="page-body"><div className="container-xl"><div className="page-header d-print-none"><div className="row align-items-center"><div className="col"><div className="page-pretitle">Overview</div><h2 className="page-title">Dashboard</h2></div><div className="col-auto ms-auto"><button className="btn btn-primary">Create report</button></div></div></div>
        <div className="row row-deck row-cards">{metrics.map(([label, value, change, color]) => <div className="col-sm-6 col-lg-3" key={label}><div className="card"><div className="card-body"><div className="subheader">{label}</div><div className="h1 mb-2">{value}</div><div className={color}>{change} <span className="text-secondary">from last month</span></div></div></div></div>)}
          <div className="col-lg-8" id="analytics"><div className="card"><div className="card-header"><h3 className="card-title">Traffic overview</h3></div><div className="card-body"><div className="d-flex align-items-end gap-3" style={{ height: 240 }}>{[42,69,51,82,64,91,75,100,87,71,95,84].map((height, index) => <div key={index} className="bg-primary rounded-top flex-fill" style={{ height: `${height}%`, opacity: 0.45 + index / 20 }} />)}</div></div></div></div>
          <div className="col-lg-4"><div className="card"><div className="card-header"><h3 className="card-title">Activity</h3></div><div className="list-group list-group-flush list-group-hoverable">{activity.map(([title, time]) => <div className="list-group-item" key={title}><div className="row align-items-center"><div className="col-auto"><span className="status-dot status-dot-animated bg-green d-block" /></div><div className="col text-truncate"><span className="text-body d-block">{title}</span><small className="d-block text-secondary text-truncate mt-n1">{time}</small></div></div></div>)}</div></div></div>
          <div className="col-md-6" id="projects"><div className="card"><div className="card-header"><h3 className="card-title">Project progress</h3></div><div className="card-body">{[['Design system','82%',''],['Mobile app','64%','bg-green'],['Content audit','39%','bg-yellow']].map(([name, value, color]) => <div className="mb-3" key={name}><div className="d-flex justify-content-between"><span>{name}</span><span>{value}</span></div><div className="progress"><div className={`progress-bar ${color}`} style={{ width: value }} /></div></div>)}</div></div></div>
          <div className="col-md-6" id="team"><div className="card"><div className="card-header"><h3 className="card-title">Team members</h3></div><div className="card-body"><div className="avatar-list avatar-list-stacked"><span className="avatar avatar-lg" style={{ backgroundImage: "url('/static/avatars/071f.jpg')" }} /><span className="avatar avatar-lg" style={{ backgroundImage: "url('/static/avatars/063m.jpg')" }} /><span className="avatar avatar-lg" style={{ backgroundImage: "url('/static/avatars/056f.jpg')" }} /><span className="avatar avatar-lg bg-primary text-white">+9</span></div><p className="text-secondary mt-3 mb-0">12 people are collaborating on active projects.</p></div></div></div>
        </div></div></main></div></div>
}
